version: "1.0"

services:
  mention-app:
    container_name: mention
    image: mention
    ports:
      - "8080:8080"
    networks:
      - mention-network

  mention-db:
    container_name: mention-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mention
    ports:
      - "5433:5432"
    networks:
      - mention-network
volumes:
  mention-db:

networks:
  mention-network:
    driver: bridge